### ISSUE TITLE
Help bug

### ISSUE THREAD

**Issue by OctoBanon-Main** [HONAK0/Sourim#1]
Help command intermittently crashes the system

**Comment by HONAK0** [comment]
Try to update gcc.

**Comment by OctoBanon-Main** [comment]
I already have latest version gcc

**Comment by HONAK0** [comment]
I don't know, it works fine for me.

**Comment by OctoBanon-Main** [comment]
Maybe this is floating bug

**Comment by HONAK0** [comment]
How much RAM is installed for the virtual machine?

**Comment by OctoBanon-Main** [comment]
Idk

**Comment by OctoBanon-Main** [comment]
512 MB RAM setted in VM

**Comment by HONAK0** [comment]
Try running it on a real computer xd

**Comment by OctoBanon-Main** [comment]
Okay this issues thread useless, i'm closing this. Waiting new update
